// Generated by scripts/build-images.py. Do not edit by hand.
export const images = {
  "hero-kick": {
    "w": 853,
    "h": 1280,
    "widths": [
      160,
      360,
      720,
      853
    ],
    "blur": "data:image/webp;base64,UklGRqIAAABXRUJQVlA4IJYAAADwBQCdASoYACQAPu1wr1MppiQipWmZMB2JYwCzs75JDzI5YR7gbh0hlLqQwFlD2rQNSDIFKvkaAAD+7TScOkedG7TE1cpUDmVMNU2KK8K1ci4OimWRQ4J+p2xk+ShlxyiloTrF/mbbfMOoVbDFuUTBCcVPV1kz7d1Ce6GbQFY4yCr5zvC+PLrW0KIdD7O1q+Da17cAAAA="
  },
  "kick-side": {
    "w": 853,
    "h": 1280,
    "widths": [
      160,
      360,
      720,
      853
    ],
    "blur": "data:image/webp;base64,UklGRpAAAABXRUJQVlA4IIQAAADQBQCdASoYACQAPtlcok2oJaMiNVv8AQAbCWMAsOwhYBQ7pdliguBNl7vibaCy+qxEkRr/B2AAAP7S+DiTdqhV5YMOBSIwaHA74h/WtxOww+if4eyM9RLZjJO1HZQvz7uBqAHHQJxpfNMlukWW3zgc6p3CZQyr0ZF3oiSls2LigkkAAAA="
  },
  "stance": {
    "w": 853,
    "h": 1280,
    "widths": [
      160,
      360,
      720,
      853
    ],
    "blur": "data:image/webp;base64,UklGRp4AAABXRUJQVlA4IJIAAAAwBQCdASoYACQAPu1orE+ppiQiKqoBMB2JYwC9WAytp0rLz6WBkdGNX+opOp+9HIcFYAD2QveUlzZ89Zd+/53roIAtH95n0um+MozK1ynn5ZP7oehO8eyEz070e+Qp1H/O3yWiSaLeRnVEP0ehnHwhUb6Fez1p9qia7H2ulmMZnJAWUStUOasDjATYAq52jNYAAA=="
  },
  "master-portrait": {
    "w": 1812,
    "h": 2068,
    "widths": [
      160,
      360,
      720,
      1080,
      1600
    ],
    "blur": "data:image/webp;base64,UklGRqIAAABXRUJQVlA4IJYAAACwBQCdASoYABsAPu1aqE2ppKQiN/VYATAdiWwAnTMOMDe4W4ADCkW++SafEZBSOF5HouElAwAA/YTClWYhUym6SunJI3q2BR0Uucwdp8AR7oIjveD5gCty4krQpQ7kIMOnV2FOAxjKHit6EVYVTpEsmFTlNOoODRKNNmW+JCTi7GfoV0ShzG0tK2YILCad6hy3dIDIAAA="
  },
  "master-dojo": {
    "w": 3072,
    "h": 3769,
    "widths": [
      160,
      360,
      720,
      1080,
      1600
    ],
    "blur": "data:image/webp;base64,UklGRq4AAABXRUJQVlA4IKIAAACwBQCdASoYAB0APu1qrVCppaQiqAqpMB2JZADBDoR3MLcHPJzxYZTYK3xKuabhwKzYwEHjDAAA/vAKYEGbxrah+Xfd9oaPgY+hsnuO7/ewLKHySPJ9dbozi3pEGMYAayqxwN65/3UWB2adB6QMl2FpIEhf1sJndi6uhhthfBd1Vd2zuxye9wjnX3yXl5te9DAvaQ35nwudiSBCjNWx40cAAAA="
  },
  "sensei-visit": {
    "w": 1080,
    "h": 1350,
    "widths": [
      160,
      360,
      720,
      1080
    ],
    "blur": "data:image/webp;base64,UklGRoAAAABXRUJQVlA4IHQAAADQBACdASoYAB4APu1mqk2ppaQiMAgBMB2JZQC06B5xaI0eZCK6mt2OpGk6r0KMAAD+jOmJowZEgBLFMZwO4QhsJFNfbmGeS71k0md+OUFBDcLToeGncf2IZd6JsWEkER9dETGxw8eeOdaVvqtQlboVxsYAAA=="
  },
  "team-flag": {
    "w": 4096,
    "h": 3072,
    "widths": [
      160,
      360,
      720,
      1080,
      1600
    ],
    "blur": "data:image/webp;base64,UklGRowAAABXRUJQVlA4IIAAAADwBACdASoYABIAPu1oqk+ppaOiMBgIATAdiWQAsR80OygSJkwa0ojteKuQON+iCIAA/sSkTyfcJKThRrlopo6rUXR1/HzIgWrQj8LV3tgR6tOlsoEeNZSIvw1tCwBxQzp8Aig2FE0SSA22FcktfLCGLRjDBcOCsRs+62WuNv0AAA=="
  },
  "championship-poster": {
    "w": 3508,
    "h": 2508,
    "widths": [
      160,
      360,
      720,
      1080,
      1600
    ],
    "blur": "data:image/webp;base64,UklGRowAAABXRUJQVlA4IIAAAACwBACdASoYABEAPu1opk2ppiMiMBgMATAdiWgAnTLiKQAkukqGGizGRYXV35CQAP6U3WYMwKR/XBWc2xeJuYNWll/AmwpWEXZxnE/+TSEC9DMB3ODfF2ulsLFTK/f5PptwTMf+U6ZR92yBzY+7jFgYsxnUm5YzUgAOdu/hNXwAAA=="
  },
  "medal-1": {
    "w": 3072,
    "h": 4096,
    "widths": [
      160,
      360,
      720,
      1080,
      1600
    ],
    "blur": "data:image/webp;base64,UklGRtgAAABXRUJQVlA4IMwAAAAQBgCdASoYACAAPu1qrVCppaQiqAqpMB2JbACsMoMsdOSjup5YHlJ8yFM72z2om2BBx9Z6eb35xAwA/vonjHbSuuhJjJkWU/GT1Aox7xBAaRML18WO7rTycnXcYuFQlhrTkcfuS3PPlNMfE9N6opWItcF6ZPfvDM0F+AxVWmz+ywqUyTR/Zqsze9oU6P97ohSc5UqjOhvRKqLEIsV9hMh61jBt+XCU5XGr6mOJ28GxBk/JD6VnmFQIz7jGQGWYHNUmXd71vclNjrDgAAA="
  },
  "medal-2": {
    "w": 3072,
    "h": 4096,
    "widths": [
      160,
      360,
      720,
      1080,
      1600
    ],
    "blur": "data:image/webp;base64,UklGRtgAAABXRUJQVlA4IMwAAABQBgCdASoYACAAPu1mq06ppaQiKA1RMB2JbAC7MvUsqcAYsgZh+LlixUVQk1SXA3mlFCnJIByMdee0YAD+9hPNMJXbfjcvzmPHkSgHbJwl6TnrimeeH4JlrjI6TZ/46vwPHHWbPUGT0HtQNlze1aMIn71J86Mk1f4bi4pw+GZmKk/JznY3kRbB2OFrHerGV86FnT0mTRPWr8Kx5DsS0OsS/XjvpDx5GgoCh9ps2Bm0bqHy2xhHOpNHmy/KA+Y95z1KjV6rjL8PZzA0sAA="
  },
  "medal-4": {
    "w": 3072,
    "h": 4096,
    "widths": [
      160,
      360,
      720,
      1080,
      1600
    ],
    "blur": "data:image/webp;base64,UklGRr4AAABXRUJQVlA4ILIAAACQBQCdASoYACAAPu1orVEppaQiqAqpMB2JZgCdMoM8qNymvCSd07Svz+sTUD/5+LixkaE6gAD4Qihza9uL8CEVgquiBjiZXeVNEsFUpLEaZUqLu1AbwYXZDUvzTpT83v2/ytCGD8o/8DXVqLJy830xbz04IE3W97Q6zOJHGbnDFeVf7Vxz4PfTEvZRCNwwk7gkV0MDwsKLTMkiGIlAz+oWDnzDAydC7Ds1vOo73LwgwAAA"
  },
  "medal-5": {
    "w": 3072,
    "h": 4096,
    "widths": [
      160,
      360,
      720,
      1080,
      1600
    ],
    "blur": "data:image/webp;base64,UklGRsAAAABXRUJQVlA4ILQAAADQBQCdASoYACAAPu1qr1CppiQiqAqpMB2JbAC7L1AC3+EbQrlHr5kq3dhc35ZE87fHo2CrSKCAAP7x/VxBKMvra1j7amaqWzmnN0wAnnxGF9lNNhQQ7dxoN4WXdXaMUrN0ENbPiE6Hmr8k1Umow+IH8Su2BJuGoJjxce5OxEfcWbLJiAnnLQ+kGsFP+VuahVdERODV6hvUkHLs7UzZ9qU8+7xTfmab+E/jxY3ftf2BTGcAAAA="
  },
  "medal-6": {
    "w": 3072,
    "h": 4096,
    "widths": [
      160,
      360,
      720,
      1080,
      1600
    ],
    "blur": "data:image/webp;base64,UklGRr4AAABXRUJQVlA4ILIAAABQBQCdASoYACAAPu1qrlCppaQiqAqpMB2JagC7MoAKQzgFeuP+3QIa9uPCruHDqJjVcaAA/voVl+RaHC+QPYVdbwlk3W+mEDXw8YZYOfUJxEF8SaUbFbVBxPOVZebKP1lemWqQAFatO7RPu1VSsTiOZCBLc2TXDcsQ5OJrLn6suASUxP3krdxtPFam4uYaflO3ouOYSGwuwxqPsUUtY17KokWgsBRJIZ0xC8GzC89owAAA"
  },
  "medal-7": {
    "w": 3072,
    "h": 4096,
    "widths": [
      160,
      360,
      720,
      1080,
      1600
    ],
    "blur": "data:image/webp;base64,UklGRsIAAABXRUJQVlA4ILYAAACQBQCdASoYACAAPu1qr1CppiQiqAqpMB2JbACsMoAKH/x0hAIZ9K3RdPEGJhGuARhL6En6gAD+WEWcJU2me950ZU8KcX7iJilcl3BZEc5u5kC0jWUUln9PLC+TAnCNSuFu0hlu3FyjWSZtxNPsPmpmx4ms9il5NM6R2VIiE5/LBBgjVB8KxLr4DTvHDrPt1Xd+OxPD0GDH6eyU7r7OsZDiOAmzQWS7PpdrhFpf/fypSyXdZgAAAA=="
  },
  "medal-8": {
    "w": 3072,
    "h": 4096,
    "widths": [
      160,
      360,
      720,
      1080,
      1600
    ],
    "blur": "data:image/webp;base64,UklGRsAAAABXRUJQVlA4ILQAAADwBQCdASoYACAAPu1sqlGppaOiqAqpMB2JZgCpJvUwtOSgNFhZdeDvexCporFFJ0OZ7hpw1KitAAD+sNqRX/90KGrvfEescYfNmZBu+EE38n9s9wIhC5wtLKA2+6gjm+c+4wdFJOfMAA4XDlCG3+40dY1Vcr+vpBa7wrG7yeKW204TJ+G9qIVlzrbszMr2JJ41wI4MMdEfIXeUwlBm9FL9nNG5U1bB/KcWAERAyXQNWw70AAA="
  },
  "medal-9": {
    "w": 3072,
    "h": 4096,
    "widths": [
      160,
      360,
      720,
      1080,
      1600
    ],
    "blur": "data:image/webp;base64,UklGRsAAAABXRUJQVlA4ILQAAAAQBgCdASoYACAAPu1qr1CppaQiqAqpMB2JbACsMuHVEDwtUbBoksxLTC+Y+Rh890ltVwwAoydH4IAA/rOvSCeCxmNxywvV9kPadblTzmtncKXaTEbDNZL2LfbxutVoQWSWZ4kMiStZ8nfObzwPt6KyRE787JaoPRleGdhtHFIGsshhoVs7lgfw3k9yaUsxzh22G2zS81J/OlIQbvdO/wxDH4w084rEsBKQ0riEYSmKymZ9gAA="
  },
  "avatar-1": {
    "w": 861,
    "h": 861,
    "widths": [
      160,
      360,
      720,
      861
    ],
    "blur": "data:image/webp;base64,UklGRroAAABXRUJQVlA4IK4AAACwBQCdASoYABgAPu1gqk2ppaQiMBgMATAdiWYArDKAAYA06HwxG7ISdtOeY6WJE87ViAEFwwAA/e6VWODIXlHJVCS6qfFPQZ887kxdxtggtZHuvlmH6PeZgeHX3Y+KlBjfbGSSKrC6fEWOpoqc3C3Rr7k6XxPsVxfFoCxHI7Dk8Tyi4CNUuV7vhVMWx+Xw5hmhPaZ+810LPpOk2Ixnj0t2CrQ5wJrgbx1RPok0AAA="
  },
  "avatar-2": {
    "w": 921,
    "h": 921,
    "widths": [
      160,
      360,
      720,
      921
    ],
    "blur": "data:image/webp;base64,UklGRq4AAABXRUJQVlA4IKIAAAAwBQCdASoYABgAPu1sr1EppaQiqAqpMB2JZACdMoMtQGO7xtYVFtsySTb3Rp2/5idfAAD+2GOmVNGuLEpPu7IIZLqSAdqgzXmwxzkyfekt6hHC5Dr+6rLBN8ssXZgSIlDx7k2w2xJG0RnRKSqJxpLkp+vNJZIpucgX8y9M2CD3dcDnDUHrsIcfU/v3NpzOU4zU473L7u4foEwUWiPwI9kAAAA="
  },
  "avatar-3": {
    "w": 491,
    "h": 492,
    "widths": [
      160,
      360,
      491
    ],
    "blur": "data:image/webp;base64,UklGRrAAAABXRUJQVlA4IKQAAABQBQCdASoYABgAPuVip02pJiOiMAwBIByJagCdMoPKqygCSvYlw3UbEZUIfjksC+9l2iAA/oPNepsBwvhR6mwjONGyBb27q+jmb3l+/aOmvuPKkHJhlmYl3o3bwwIJ6OwtmaUH8REyH0Yk92QvAoEqaHFPsd4Q1cNzSWxvgWcq3aQEAMlyFyTYBE6peGUrWQwkRhf7OyS6YHnkmZFBVc84UAAAAA=="
  },
  "shihan-certificate": {
    "w": 2349,
    "h": 1580,
    "widths": [
      160,
      360,
      720,
      1080,
      1600
    ],
    "blur": "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAADQAwCdASoYABAAPu1krU2ppaSiMAgBMB2JZgCdMoR3ACFLVvvRbrAA99PQ6LQc5knN74F97vwKp0Y59/CyNhCEbV2OSfW6tDYC7EsD3GTqL08JDAvubfQC5tjO768iqEt7tEpykpUqDuLD6P/egAAA"
  },
  "world-record": {
    "w": 960,
    "h": 1280,
    "widths": [
      160,
      360,
      720,
      960
    ],
    "blur": "data:image/webp;base64,UklGRowAAABXRUJQVlA4IIAAAACwBACdASoYACAAPu1srlEppaQiqAqpMB2JQBfJBhEVYmNrg9/D1dop3RZfYndQAP7Tm45blglN35dRtNCcyijk+q+nRVwTGopqWPocRUG5hkLxBYRuPN97FkXbeeq7FNPY8TnR9ZhZ9J2xYSXSYQOkdqGEzHibGwmc/WdR9nSGAA=="
  },
  "honour-3": {
    "w": 1056,
    "h": 1600,
    "widths": [
      160,
      360,
      720,
      1056
    ],
    "blur": "data:image/webp;base64,UklGRtIAAABXRUJQVlA4IMYAAAAQBwCdASoYACQAPtVYoU2oJSMiOrmYAQAaiWYAnTMRugBIoqOU4d7nIuPySpcNwr1aHWtgzAP8qKr2j/2t2+AzwAD+6oF90ng6Co2Vl7nTgH5LC9C8bMC/zLUxxBU3MeRJpMU9cvZKdNjJLEz60iIUya31x/E7hM/+1TRN8dORWg7d/gkcsb4bdQ1P6J1gwsjRB8dnDjOSWXwlkzZmvBn7QO2T7J46mu4hT5HaSEJo4JFDIwhuqQwcPz1IDOEoGSWpKZmAoAA="
  },
  "community": {
    "w": 2864,
    "h": 1624,
    "widths": [
      160,
      360,
      720,
      1080,
      1600
    ],
    "blur": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAAAwBACdASoYAA4APu1mqk4ppaOiMAgBMB2JYgCdMoADTdXmkkrZXeS1gQAA+DsgCDLRvml/aoNMmVPTerVVsU8UNJq6cajZRcEzCf4aBqZSV9tjoxYK/2S1/OvyhtyqgAA="
  },
  "press-malaysia": {
    "w": 1284,
    "h": 1759,
    "widths": [
      160,
      360,
      720,
      1080,
      1284
    ],
    "blur": "data:image/webp;base64,UklGRqIAAABXRUJQVlA4IJYAAAAQBQCdASoYACEAPuVipk2pJaOiNVgIASAciUAY3oLN1iIHXQWfxB5sXwaVDKTvvKlAAP7q+Nhjvh/MdZ6NPQyQdOVAW8OOcPTyDM2s95aDVp1ZEwsiHtcYhgFrIIfR1l6xuR+zI1PLrpt6xdczFTS+Ge6HUjCJ05Rf9P/4bg3mrSYDYbQQzRA84bWrCSmffM4lBABAAAA="
  },
  "press-udayavani": {
    "w": 604,
    "h": 563,
    "widths": [
      160,
      360,
      604
    ],
    "blur": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAADQBACdASoYABYAPuFepk2opSOiN/qoARAcCWcAy6Qh8N6JDjfRHHeolWRlwDFwIAD+8ECcK+jbDPdYYiuqyDZewwPD8qu8rgkLYbx7GOLmAOqjXnHPoijWFMAAAA=="
  },
  "press-vijaya": {
    "w": 654,
    "h": 1229,
    "widths": [
      160,
      360,
      654
    ],
    "blur": "data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAACwBQCdASoYAC0APuliqU2pJaQiNVgIASAdCWUAAMLj20Pq3eR3qQVFNShZmtMR8BOwUmXTkAAA/vHzrrRiyRdkXIGUxPnIjzHei7Lqi8FkbaxV8Ldcpr1hFcIcpOH6MLvI5eL6+oNfm7eCxTKQjm5o0vNpATAA"
  },
  "press-international": {
    "w": 1152,
    "h": 1152,
    "widths": [
      160,
      360,
      720,
      1080,
      1152
    ],
    "blur": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAACQBACdASoYABgAPu1iqU2ppaOiMAgBMB2JZwDKAB6PnIsx8LZGhOF+dyuz5AAA/tOFzwhhKYXSO+pkSpEg7ce2vHg20KULFsaeAAAA"
  },
  "press-selected": {
    "w": 352,
    "h": 556,
    "widths": [
      160,
      352
    ],
    "blur": "data:image/webp;base64,UklGRqgAAABXRUJQVlA4IJwAAADwBQCdASoYACYAPu1sqVAppiOiqrgMATAdiWMAxPkMwQCowXOEzP/8xuuRlsvqyU7wue+ZtLosgAD+58CMzCxuRVcW9IY7m/XjMDeudG/3ohQ/b2iq7GZv7F+4dlSAh0CLUCqT3ttPaAp04BJhM+CBjq64Q5F5tLblruZ2t8fsXNHBCMp1yJmNaMDnbNdbB2FAXry0snzKZnAAAAA="
  },
  "press-honour": {
    "w": 1079,
    "h": 1049,
    "widths": [
      160,
      360,
      720,
      1079
    ],
    "blur": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAAAwBACdASoYABcAPu1kqU2ppaQjMAgBMB2JZwAAXggca/+DzekBTMCOqIAA/ustrzQx1I5qfP+qw5neOmDlLUAi8yY2d2WmCW/h/eAA"
  }
} as const;

export type ImageName = keyof typeof images;
