"""Builds responsive AVIF + WebP images and blur placeholders from source-images-original/.

Run: python scripts/build-images.py  (requires Pillow with AVIF support)
"""
import base64
import io
import json
import os
from concurrent.futures import ProcessPoolExecutor

from PIL import Image, ImageFile, ImageFilter, ImageOps

ImageFile.LOAD_TRUNCATED_IMAGES = True

SRC = "source-images-original"
OUT = "client/public/images"
# Small widths serve thumbnails and avatars; large ones serve retina screens.
WIDTHS = (160, 360, 720, 1080, 1600)
WEBP_QUALITY = 70
AVIF_QUALITY = 52

# name: (source file, crop box as fractions (left, top, right, bottom) or None)
IMAGES = {
    "hero-kick": ("C7357559-EEBC-4676-909F-E0FB39F2F2A2.JPG", None),
    "kick-side": ("AD0EBAF1-E183-4A50-ABBB-A30C0EAFF084.JPG", None),
    "stance": ("20DA8E9B-179B-449F-93AE-55AD2F2F2A95.JPG", None),
    "master-portrait": ("IMG_0281.JPG", None),
    "master-dojo": ("IMG_7733.JPG", (0, 0.08, 1, 1)),
    "sensei-visit": ("IMG_4338.JPG", None),
    "team-flag": ("IMG_7712.JPG", None),
    "championship-poster": ("IMG_7895.JPG", None),
    "medal-1": ("IMG_7713.JPG", None),
    "medal-2": ("IMG_7709.JPG", None),
    "medal-4": ("IMG_7702.JPG", None),
    "medal-5": ("IMG_7715.JPG", None),
    "medal-6": ("IMG_7706.JPG", None),
    "medal-7": ("IMG_7697.JPG", None),
    "medal-8": ("IMG_7716.JPG", None),
    "medal-9": ("IMG_7699.JPG", None),
    # Square face crops for the small avatars in the hero.
    "avatar-1": ("IMG_7713.JPG", (0.54, 0.28, 0.82, 0.49)),
    "avatar-2": ("IMG_7709.JPG", (0.50, 0.18, 0.80, 0.405)),
    "avatar-3": ("IMG_7699.JPG", (0.445, 0.36, 0.605, 0.48)),
    "shihan-certificate": ("IMG_7720.JPG", (0.06, 0.03, 0.93, 0.97)),
    "world-record": ("IMG_1261.JPG", None),
    "honour-3": ("IMG_4362.JPG", None),
    "community": ("IMG_3595.JPG", None),
    "press-malaysia": ("IMG_7787.PNG", None),
    "press-udayavani": ("IMG_7827.JPG", None),
    "press-vijaya": ("IMG_7821.JPG", (0, 0.04, 1, 1)),
    "press-international": ("IMG_4234.JPG", None),
    "press-selected": ("IMG_6863.JPG", None),
    "press-honour": ("IMG_0824.JPG", (0.08, 0.27, 0.92, 0.73)),
}


def placeholder(im):
    """~300-byte blurred preview inlined into the page, shown while the real image loads."""
    small = im.resize((24, max(1, round(im.height * 24 / im.width))), Image.LANCZOS).filter(ImageFilter.GaussianBlur(1))
    buf = io.BytesIO()
    small.save(buf, "WEBP", quality=40)
    return "data:image/webp;base64," + base64.b64encode(buf.getvalue()).decode()


def build(item):
    name, (src, crop) = item
    im = ImageOps.exif_transpose(Image.open(os.path.join(SRC, src))).convert("RGB")
    if crop:
        w, h = im.size
        im = im.crop((int(crop[0] * w), int(crop[1] * h), int(crop[2] * w), int(crop[3] * h)))
    widths = sorted({w for w in WIDTHS if w < im.width} | {min(im.width, WIDTHS[-1])})
    for w in widths:
        out = im.resize((w, round(im.height * w / im.width)), Image.LANCZOS)
        out.save(os.path.join(OUT, f"{name}-{w}.webp"), "WEBP", quality=WEBP_QUALITY, method=6)
        out.save(os.path.join(OUT, f"{name}-{w}.avif"), "AVIF", quality=AVIF_QUALITY, speed=4)
    return name, {"w": im.width, "h": im.height, "widths": widths, "blur": placeholder(im)}


def main():
    os.makedirs(OUT, exist_ok=True)
    for f in os.listdir(OUT):
        if f.endswith((".webp", ".avif")):
            os.remove(os.path.join(OUT, f))
    with ProcessPoolExecutor() as pool:
        results = list(pool.map(build, IMAGES.items()))
    manifest = dict(results)
    for name, m in results:
        print(f"{name:22} {m['w']}x{m['h']} -> {m['widths']}")
    with open("client/src/data/images.ts", "w") as fh:
        fh.write("// Generated by scripts/build-images.py. Do not edit by hand.\n")
        fh.write("export const images = ")
        json.dump(manifest, fh, indent=2)
        fh.write(" as const;\n\nexport type ImageName = keyof typeof images;\n")


if __name__ == "__main__":
    main()
